version: "{build}"

skip_commits:
  message: /\[skip ci\]/


image:
  - Visual Studio 2017

platform: x64

install:
  - cmd: appveyor DownloadFile https://github.com/libusb/libusb/releases/download/v1.0.21/libusb-1.0.21.7z -FileName libusb.7z
  - cmd: 7z x libusb.7z
  - cmd: C:\Python36-x64\python -m pip install --upgrade pip setuptools pyinstaller --ignore-installed
  - cmd: C:\Python36-x64\python setup.py install


build_script:
  - cmd: copy extra\installer-licenses.txt LICENSE.txt
  - cmd: C:\Python36-x64\Scripts\pyinstaller --add-data MS64\dll\*;. --clean -F liquidctl\cli.py --name liquidctl --distpath .\py_dist
  - cmd: copy extra\installer-licenses.txt py_dist\LICENSE.txt

test: off

artifacts:
  - path: py_dist\*
